-- Zones
INSERT INTO zone(id, name) VALUES (nextval('hibernate_sequence'), 'Zone Est');
INSERT INTO zone(id, name) VALUES (nextval('hibernate_sequence'), 'Zone Centre');
INSERT INTO zone(id, name) VALUES (nextval('hibernate_sequence'), 'Zone Sud');
INSERT INTO zone(id, name) VALUES (nextval('hibernate_sequence'), 'Zone Nord');
INSERT INTO zone(id, name) VALUES (nextval('hibernate_sequence'), 'Zone Ouest');

-- Regions
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Dakar', 'DK', id FROM zone WHERE name='Zone Ouest';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Diourbel', 'DL', id FROM zone WHERE name='Zone Centre';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Fatick', 'FK', id FROM zone WHERE name='Zone Centre';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Kaffrine', 'KF', id FROM zone WHERE name='Zone Centre';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Kaolack', 'KL', id FROM zone WHERE name='Zone Centre';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Kolda', 'KD', id FROM zone WHERE name='Zone Sud';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Kédougou', 'KG', id FROM zone WHERE name='Zone Est';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Louga', 'LG', id FROM zone WHERE name='Zone Nord';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Matam', 'MT', id FROM zone WHERE name='Zone Nord';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Saint-Louis', 'SL', id FROM zone WHERE name='Zone Nord';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Sédhiou', 'SD', id FROM zone WHERE name='Zone Sud';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Tambacounda', 'TC', id FROM zone WHERE name='Zone Est';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Thiès', 'TH', id FROM zone WHERE name='Zone Ouest';
INSERT INTO region(id, name, code, zone_id) SELECT nextval('hibernate_sequence'), 'Ziguinchor', 'ZG', id FROM zone WHERE name='Zone Sud';

-- Departments
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Bakel', 'BK', id FROM region WHERE name='Tambacounda';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Bambey', 'BB', id FROM region WHERE name='Diourbel';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Bignogna', 'BG', id FROM region WHERE name='Ziguinchor';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Birkilane', 'BR', id FROM region WHERE name='Kaffrine';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Bounkiling', 'BL', id FROM region WHERE name='Sédhiou';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Dagana', 'DG', id FROM region WHERE name='Saint-Louis';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Dakar', 'DK', id FROM region WHERE name='Dakar';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Diourbel', 'DB', id FROM region WHERE name='Diourbel';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Fatick', 'FK', id FROM region WHERE name='Fatick';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Foundiougne', 'FD', id FROM region WHERE name='Fatick';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Gossas', 'GS', id FROM region WHERE name='Fatick';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Goudiry', 'GY', id FROM region WHERE name='Tambacounda';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Goudomp', 'GP', id FROM region WHERE name='Sédhiou';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Guédiawaye', 'GG', id FROM region WHERE name='Dakar';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Guinguinéo', 'GD', id FROM region WHERE name='Kaolack';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Kaffrine', 'KF', id FROM region WHERE name='Kaffrine';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Kanel', 'KN', id FROM region WHERE name='Matam';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Kaolack', 'KL', id FROM region WHERE name='Kaolack';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Kébémer', 'KP', id FROM region WHERE name='Louga';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Kédougou', 'KU', id FROM region WHERE name='Kédougou';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Kolda', 'KB', id FROM region WHERE name='Kolda';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Koumpentoum', 'KG', id FROM region WHERE name='Tambacounda';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Kounghel', 'KD', id FROM region WHERE name='Kaffrine';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Linguère', 'LN', id FROM region WHERE name='Louga';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Louga', 'LG', id FROM region WHERE name='Louga';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'M''bour', 'MH', id FROM region WHERE name='Thiès';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Malem-Hodar', 'MT', id FROM region WHERE name='Kaffrine';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Matam', 'MK', id FROM region WHERE name='Matam';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Mbacké', 'MR', id FROM region WHERE name='Diourbel';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Médina Yoro Foulah', 'YF', id FROM region WHERE name='Kolda';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Nioro du Rip', 'NR', id FROM region WHERE name='Kaolack';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Oussouye', 'OU', id FROM region WHERE name='Ziguinchor';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Pikine', 'PK', id FROM region WHERE name='Dakar';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Podor', 'PD', id FROM region WHERE name='Saint-Louis';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Ranérou', 'RN', id FROM region WHERE name='Matam';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Rufisque', 'RF', id FROM region WHERE name='Dakar';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Saint-Louis', 'SL', id FROM region WHERE name='Saint-Louis';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Salemata', 'SM', id FROM region WHERE name='Kédougou';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Saraya', 'SY', id FROM region WHERE name='Kédougou';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Sédhiou', 'SD', id FROM region WHERE name='Sédhiou';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Tambacounda', 'TC', id FROM region WHERE name='Tambacounda';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Thiès', 'TH', id FROM region WHERE name='Thiès';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Tivaouane', 'TV', id FROM region WHERE name='Thiès';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Vélingara', 'VL', id FROM region WHERE name='Kolda';
INSERT INTO department(id, name, code, region_id) SELECT nextval('hibernate_sequence'), 'Ziguinchor', 'ZG', id FROM region WHERE name='Ziguinchor';
