export const GRAPHIC_COLOR_BLUE = '#3c7ebb'
export const GRAPHIC_COLOR_RED = '#c94545'
export const GRAPHIC_COLOR_YELLOW = '#f2b704'
export const GRAPHIC_COLOR_GREEN = '#479519'
export const GRAPHIC_COLOR_GRAY1 = '#898989'
export const GRAPHIC_COLOR_GRAY2 = '#c1c1c1'
export const GRAPHIC_COLOR_GRAY3 = '#e1e1e1'

export const GRAPHIC_MAIN_COLORS = [
  GRAPHIC_COLOR_BLUE,
  GRAPHIC_COLOR_RED,
  GRAPHIC_COLOR_YELLOW,
  GRAPHIC_COLOR_GREEN,
]
